test: fix tests forward for 1.16.x (#1655)
# Summary

1.16 added a `space` param to gPA and changed an error message. This PR updates the web3.js tests to handle that, and a whole lot more fiddling with object shapes and strictness.

# NOTE

The _really_ bad thing about this is that when the tests break, you get this inscrutable error from Jest:

```
FAIL   Unit Test (Node)  src/rpc-methods/__tests__/get-multiple-accounts-test.ts
  ● Test suite failed to run

    DataCloneError: Symbol(jest.asymmetricMatcher) could not be cloned.

      at reportSuccess (../../node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/threadChild.js:98:34)
```

I think this is because of the presence of `BigInts` and Jest's inability to…

```
TypeError: Do not know how to serialize a BigInt
```

I haven't filed a bug with Jest yet, but the workaround I have is to:

* Convert all of the `toStrictMatch()` to `toMatchObject()`
* Re-run the tests and figure out what broke
* Undo undo undo to put them all back
* Fix the problem

# Test Plan

```
pnpm turbo test:unit:browser
pnpm turbo test:unit:node
```